name: CI/CD - Projeto Lari 

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Verificar projeto
        run: echo "CI funcionando com sucesso "

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy do site
        run: echo "Deploy realizado com sucesso "
